package.json
src/middleware.js

Wrap middleware response in try/catch.

Error Handling

---

package.json
src/http.js

It wasn't being imported before

Use isomorphic fetch

---

package.json
src/api.js
src/http.js

add destroy method for deletes, allow api methods to take options

---

package.json
src/middleware.js
test/middleware.test.js

send success to client reducer first

---

package.json
src/middleware.js

Postfail success

---

docs.md
package.json
src/LP_API.js

added docs for LP_API

---

.gitignore
package.json
yarn.lock

Add test coverage

---

docs.md
package.json
src/is-authenticated-with-context.js
src/is-authenticated.js

updated docs for is authenticated (& with context). updated function to check for presence of token
resolves #37

is authenticated docs

---

package.json
src/utils.js
test/is-authenticated.test.js
test/middleware.test.js
test/set-from-request.test.js

And some inline comments.
Resolves #44 and #45

Add tests for `isAuthenticated`

---

docs.md
package.json
src/get-authentication-context.js
test/get-authentication-context.test.js

getAuthenticationContext: add tests, check for valid token

---

README.md

Prep for stable

---

package.json
yarn.lock

The downside of keeping things modular....

Use the latest lp-requests version

---

package.json
src/middleware/middleware.js
src/utils.js

And slightly refactor the way http requests are configured

Add lp-requests as a peer dependency

---

.eslintrc
package.json
src/middleware/middleware.js
src/middleware/parse-action.js
src/request-with-key.js
src/selectors.js
src/set-from-request.js

Throw error objects instead of strings

---

package.json
src/stub-request.js
test/stub-request.test.js

Making this a patch since I think it's expected behavior.

Add default data creator func

---

docs.md
package.json
src/create-request.js
src/index.js
test/create-request.test.js

Add convenience functions for createRequest

---

docs.md
package.json
src/handlers/handle-failure.js
src/handlers/handle-response.js
test/middleware.test.js

Update docs and add tests for error action data key

---

docs.md
package.json
src/create-stub-request.js
src/middleware/middleware.js
src/middleware/parse-options.js
test/create-stub-request.test.js
test/middleware.test.js

Add error argument to createStubRequest

---

docs.md
package.json
src/create-request.js
src/create-stub-request.js
src/handlers/handle-failure.js
src/handlers/handle-response.js
src/handlers/handle-success.js
src/handlers/set-on-failure.js
src/handlers/set-on-response.js
src/handlers/set-on-success.js
src/middleware/middleware.js
src/middleware/parse-options.js
src/reducer.js
src/selectors.js
test/create-stub-request.test.js
test/middleware.test.js
yarn.lock

Resolves #126 
https://jestjs.io/docs/en/timer-mocks
`useFakeTimers` is invoked each time in order to reset the call count on `setTimeout` to 0. Otherwise it will aggregate and `clearAllTimers()` only clears timers, it doesn't reset their call count.

Add delay option to stub request

---

docs.md
package.json
src/create-stub-request.js
test/create-stub-request.test.js

Forgot about `createStubRequest` 🤦

Add type to stub action creator
